import streamlit as st
from supabase import create_client, Client
import pandas as pd
import plotly.express as px
import io
import time

# --- Configuration ---
st.set_page_config(page_title="(주)부름 건설회계", page_icon="🏗️")

# --- Constants & Mappings ---
MAPPING_RULES = {
    # (항목, 귀속) : (PDF계정과목, 회계분류)
    ("공사대금수령", "현장"): ("매출액", "매출"),
    ("공사대금수령", "본사"): ("매출액", "매출"),
    ("자재비", "현장"): ("원재료비", "공사원가"),
    ("인건비(일용/급여)", "현장"): ("노무비", "공사원가"),
    ("외주비", "현장"): ("외주비", "공사원가"),
    ("식대/회식", "현장"): ("복리후생비", "공사원가"),
    ("간식/음료", "현장"): ("복리후생비", "공사원가"),
    ("숙박비", "현장"): ("복리후생비", "공사원가"),
    ("주유/톨비", "현장"): ("운반비", "공사원가"),
    ("차량수리", "현장"): ("운반비", "공사원가"),
    ("운송/택배", "현장"): ("운반비", "공사원가"),
    ("소모품", "현장"): ("소모품비", "공사원가"),
    ("기타잡비", "현장"): ("소모품비", "공사원가"),
    ("잡자재", "현장"): ("잡자재", "공사원가"),
    ("장비렌탈", "현장"): ("장비사용료", "공사원가"),
    ("수수료", "현장"): ("수수료비용", "공사원가"),
    # 판관비 (본사)
    ("인건비(일용/급여)", "본사"): ("직원급여", "판관비"),
    ("식대/회식", "본사"): ("복리후생비", "판관비"),
    ("간식/음료", "본사"): ("복리후생비", "판관비"),
    ("주유/톨비", "본사"): ("여비교통비", "판관비"),
    ("차량수리", "본사"): ("차량유지비", "판관비"),
    ("접대/선물", "본사"): ("기업업무추진비", "판관비"),
    ("통신비/인터넷", "본사"): ("통신비", "판관비"),
    ("전기/수도/가스", "본사"): ("세금과공과", "판관비"),
    ("세금/공과금", "본사"): ("세금과공과", "판관비"),
    ("임대료", "본사"): ("지급임차료", "판관비"),
    ("사무용품", "본사"): ("소모품비", "판관비"),
    ("도서/인쇄", "본사"): ("도서인쇄비", "판관비"),
    ("수수료", "본사"): ("수수료비용", "판관비"),
}

# Extract unique items for the selectbox
ITEMS = sorted(list(set([k[0] for k in MAPPING_RULES.keys()])))

# Fixed Orders for Reports
CONSTRUCTION_COST_ORDER = [
    "원재료비", "노무비", "외주비", "복리후생비", "감가상각비", 
    "보험료", "운반비", "잡자재", "소모품비", "수수료비용", "장비사용료"
]

SGA_ORDER = [
    "직원급여", "상여금", "복리후생비", "여비교통비", "기업업무추진비", 
    "통신비", "세금과공과", "지급임차료", "차량유지비", "도서인쇄비", 
    "소모품비", "수수료비용"
]

# --- Supabase Connection ---
@st.cache_resource
def init_supabase():
    try:
        url = st.secrets["supabase"]["url"]
        key = st.secrets["supabase"]["key"]
        return create_client(url, key)
    except Exception as e:
        st.error(f"Supabase 연결 설정 오류: {e}")
        st.stop()

supabase: Client = init_supabase()

# --- Session State Initialization ---
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False

# --- Functions ---
def login(username, password):
    try:
        response = supabase.table("users").select("*").eq("username", username).eq("password", password).execute()
        if response.data:
            st.session_state.logged_in = True
            st.success("로그인 성공!")
            time.sleep(0.5)
            st.rerun()
        else:
            st.error("아이디 또는 비밀번호가 잘못되었습니다.")
    except Exception as e:
        st.error("로그인 중 오류가 발생했습니다.")
        st.warning("Supabase에 'users' 테이블이 없는 것 같습니다. 아래 SQL을 실행해주세요.")
        sql_query = """
-- Users 테이블 생성
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
-- 테스트 유저 데이터 삽입
INSERT INTO public.users (username, password) VALUES ('admin', '1234');
        """
        st.code(sql_query, language="sql")
        with st.expander("상세 에러 내용"):
            st.write(e)

def logout():
    st.session_state.logged_in = False
    st.rerun()

def show_history_page():
    st.header("내역 수정/삭제")
    try:
        response = supabase.table("transactions").select("*").order("date", desc=True).execute()
        rows = response.data
        if not rows:
            st.info("입력된 내역이 없습니다.")
        else:
            df = pd.DataFrame(rows)
            df['date'] = pd.to_datetime(df['date'])
            
            column_config = {
                "id": None,
                "created_at": None,
                "user_id": None,
                "date": st.column_config.DateColumn("날짜", format="YYYY-MM-DD"),
                "type": "구분",
                "attribution": "귀속",
                "category_raw": "항목(일상어)",
                "category_std": "계정과목(표준)",
                "account_type": "회계분류",
                "amount": st.column_config.NumberColumn("금액", format="%d원"),
                "vendor": "거래처",
                "memo": "메모"
            }
            
            edited_df = st.data_editor(
                df,
                column_config=column_config,
                use_container_width=True,
                num_rows="dynamic",
                key="history_editor"
            )
            
            if st.button("변경사항 저장하기", use_container_width=True):
                try:
                    changes = st.session_state["history_editor"]
                    for index, updates in changes["edited_rows"].items():
                        row_id = df.iloc[index]["id"]
                        supabase.table("transactions").update(updates).eq("id", row_id).execute()
                    for index in changes["deleted_rows"]:
                        row_id = df.iloc[index]["id"]
                        supabase.table("transactions").delete().eq("id", row_id).execute()
                    for new_row in changes["added_rows"]:
                        clean_row = {k: v for k, v in new_row.items() if v is not None}
                        if clean_row:
                            supabase.table("transactions").insert(clean_row).execute()

                    if changes["edited_rows"] or changes["deleted_rows"] or changes["added_rows"]:
                        st.success("수정/삭제가 완료되었습니다.")
                        time.sleep(1)
                        st.rerun()
                    else:
                        st.info("변경사항이 없습니다.")
                except Exception as e:
                    st.error(f"저장 중 오류 발생: {e}")
    except Exception as e:
        st.error("데이터를 불러오는 중 오류가 발생했습니다.")
        st.write(e)

def show_report_page():
    st.header("보고서 요약")
    
    try:
        response = supabase.table("transactions").select("*").execute()
        rows = response.data
        
        if not rows:
            st.info("데이터가 없습니다.")
            return

        df = pd.DataFrame(rows)
        df['date'] = pd.to_datetime(df['date'])
        df['amount'] = df['amount'].astype(int)
        
        # --- Data Processing ---
        income_df = df[df['type'] == '수입']
        expense_df = df[df['type'] == '지출']
        
        site_expense_df = expense_df[expense_df['attribution'] == '현장']
        hq_expense_df = expense_df[expense_df['attribution'] == '본사']
        
        total_revenue = income_df['amount'].sum()
        total_site_expense = site_expense_df['amount'].sum()
        total_hq_expense = hq_expense_df['amount'].sum()
        
        # --- Section 1: Dashboard ---
        st.subheader("1. 경영 대시보드")
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("##### 현장 vs 본사 비용 비중")
            if total_site_expense + total_hq_expense > 0:
                pie_data = pd.DataFrame({
                    "Category": ["공사원가 (현장)", "판관비 (본사)"],
                    "Amount": [total_site_expense, total_hq_expense]
                })
                fig_pie = px.pie(pie_data, values='Amount', names='Category', hole=0.4)
                st.plotly_chart(fig_pie, use_container_width=True)
            else:
                st.caption("비용 데이터가 없습니다.")

        with col2:
            st.markdown("##### 월별 지출 추이")
            if not expense_df.empty:
                expense_df['month'] = expense_df['date'].dt.strftime('%Y-%m')
                monthly_expense = expense_df.groupby('month')['amount'].sum().reset_index()
                fig_bar = px.bar(monthly_expense, x='month', y='amount', text_auto=',.0f')
                st.plotly_chart(fig_bar, use_container_width=True)
            else:
                st.caption("지출 데이터가 없습니다.")

        st.divider()

        # --- Section 2: Construction Cost Statement (공사원가명세서) ---
        st.subheader("2. 공사원가명세서 (현장)")
        
        # Calculate sums by category
        if not site_expense_df.empty:
            site_grouped = site_expense_df.groupby('category_std')['amount'].sum()
        else:
            site_grouped = pd.Series(dtype=int)

        # Enforce Fixed Order
        cost_data = []
        for category in CONSTRUCTION_COST_ORDER:
            amount = site_grouped.get(category, 0)
            cost_data.append({"항목": category, "금액": amount})
        
        cost_statement_df = pd.DataFrame(cost_data)
        
        # Add Total Row
        total_row = pd.DataFrame({'항목': ['당기총공사비용(합계)'], '금액': [total_site_expense]})
        cost_statement_final = pd.concat([cost_statement_df, total_row], ignore_index=True)
        
        st.dataframe(
            cost_statement_final,
            column_config={"금액": st.column_config.NumberColumn("금액", format="%d원")},
            use_container_width=True,
            hide_index=True
        )

        st.divider()

        # --- Section 3: Income Statement (손익계산서) ---
        st.subheader("3. 손익계산서")
        
        # 3-1. Summary
        gross_profit = total_revenue - total_site_expense
        operating_profit = gross_profit - total_hq_expense
        
        is_summary_data = {
            "항목": ["1. 매출액", "2. 매출원가 (공사원가)", "3. 매출총이익 (1-2)", "4. 판매비와관리비", "5. 영업이익 (3-4)"],
            "금액": [total_revenue, total_site_expense, gross_profit, total_hq_expense, operating_profit]
        }
        is_summary_df = pd.DataFrame(is_summary_data)
        
        st.markdown("##### 요약")
        st.dataframe(
            is_summary_df,
            column_config={"금액": st.column_config.NumberColumn("금액", format="%d원")},
            use_container_width=True,
            hide_index=True
        )

        # 3-2. SG&A Details (판관비 상세)
        st.markdown("##### 판매비와관리비 상세")
        
        if not hq_expense_df.empty:
            hq_grouped = hq_expense_df.groupby('category_std')['amount'].sum()
        else:
            hq_grouped = pd.Series(dtype=int)
            
        sga_data = []
        for category in SGA_ORDER:
            amount = hq_grouped.get(category, 0)
            sga_data.append({"항목": category, "금액": amount})
            
        sga_df = pd.DataFrame(sga_data)
        
        st.dataframe(
            sga_df,
            column_config={"금액": st.column_config.NumberColumn("금액", format="%d원")},
            use_container_width=True,
            hide_index=True
        )
        
        # --- Excel Download ---
        st.divider()
        
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
            # Sheet 1: 공사원가명세서
            cost_statement_final.to_excel(writer, sheet_name='공사원가명세서', index=False)
            
            # Sheet 2: 손익계산서 (Summary + Details)
            # Write Summary first
            is_summary_df.to_excel(writer, sheet_name='손익계산서', index=False, startrow=0)
            # Write Details below
            start_row = len(is_summary_df) + 3
            pd.DataFrame(["[판매비와관리비 상세]"]).to_excel(writer, sheet_name='손익계산서', index=False, header=False, startrow=start_row-1)
            sga_df.to_excel(writer, sheet_name='손익계산서', index=False, startrow=start_row)
            
            # Sheet 3: Raw Data
            df.to_excel(writer, sheet_name='전체데이터', index=False)
            
        st.download_button(
            label="📥 엑셀 다운로드 (세무신고용)",
            data=buffer.getvalue(),
            file_name=f"건설회계_세무신고용_{pd.Timestamp.now().strftime('%Y%m%d')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True
        )

    except Exception as e:
        st.error("보고서를 생성하는 중 오류가 발생했습니다.")
        st.write(e)

# --- UI Layout ---
if not st.session_state.logged_in:
    st.markdown("""<style>[data-testid="stSidebar"] {display: none;}</style>""", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.title("🏗️ 건설회계 시스템")
        st.subheader("로그인")
        username = st.text_input("아이디")
        password = st.text_input("비밀번호", type="password")
        if st.button("로그인", use_container_width=True):
            login(username, password)
else:
    st.sidebar.title("(주)부름 건설회계")
    st.sidebar.markdown("---")
    menu = st.sidebar.radio("메뉴", ["수입/지출 입력", "내역 수정/삭제", "보고서 요약"])
    st.sidebar.markdown("---")
    if st.sidebar.button("로그아웃"):
        logout()

    st.title("환영합니다! (주)부름 건설회계 시스템")
    st.caption("Supabase 연동됨")
    st.divider()

    if menu == "수입/지출 입력":
        st.header("수입/지출 입력")
        col1, col2 = st.columns(2)
        with col1:
            date = st.date_input("날짜")
        with col2:
            tx_type = st.radio("구분", ["지출", "수입"], horizontal=True)

        attribution = None
        if tx_type == "지출":
            attribution = st.radio("비용 귀속", ["현장", "본사"], horizontal=True)
        else:
            attribution = "본사"

        with st.form("transaction_form"):
            item = st.selectbox("항목 (일상 용어)", ITEMS)
            amount = st.number_input("금액", min_value=0, step=1000)
            vendor = st.text_input("거래처")
            memo = st.text_input("적요/메모")
            
            submitted = st.form_submit_button("저장", use_container_width=True)
            
            if submitted:
                category_std = item
                account_type = "기타"
                
                if tx_type == "지출":
                    if (item, attribution) in MAPPING_RULES:
                        category_std, account_type = MAPPING_RULES[(item, attribution)]
                    else:
                        category_std = item
                        account_type = "미분류"
                else:
                    # Income mapping
                    if (item, attribution) in MAPPING_RULES:
                        category_std, account_type = MAPPING_RULES[(item, attribution)]
                    else:
                        category_std = "매출액"
                        account_type = "매출"

                try:
                    data = {
                        "date": str(date),
                        "type": tx_type,
                        "attribution": attribution,
                        "category_raw": item,
                        "category_std": category_std,
                        "account_type": account_type,
                        "amount": amount,
                        "vendor": vendor,
                        "memo": memo
                    }
                    supabase.table("transactions").insert(data).execute()
                    st.success(f"✅ 저장되었습니다!")
                    st.info(f"매핑 결과: [{item}] -> [{category_std} ({account_type})]")
                except Exception as e:
                    st.error("저장 중 오류가 발생했습니다.")
                    st.warning("Supabase에 'transactions' 테이블이 없는 것 같습니다. 아래 SQL을 실행해주세요.")
                    sql_query = """
-- Transactions 테이블 생성
CREATE TABLE public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date DATE NOT NULL,
    type TEXT NOT NULL,
    attribution TEXT,
    category_raw TEXT,
    category_std TEXT,
    account_type TEXT,
    amount BIGINT,
    vendor TEXT,
    memo TEXT,
    user_id TEXT
);
                    """
                    st.code(sql_query, language="sql")
                    with st.expander("상세 에러 내용"):
                        st.write(e)
        
    elif menu == "내역 수정/삭제":
        show_history_page()
        
    elif menu == "보고서 요약":
        show_report_page()
