import streamlit as st
from supabase import create_client, Client
import pandas as pd
import plotly.express as px
import io
import time

# --- Configuration ---
# --- Configuration ---
st.set_page_config(page_title="세무의 모든 것", page_icon="💰", layout="wide", initial_sidebar_state="collapsed")

# --- Constants & Mappings ---
MAPPING_RULES = {
    # (항목, 귀속) : (PDF계정과목, 회계분류)
    ("공사대금수령", "현장"): ("매출액", "매출"),
    ("공사대금수령", "본사"): ("매출액", "매출"),
    ("자재비", "현장"): ("원재료비", "공사원가"),
    ("인건비(일용/급여)", "현장"): ("노무비", "공사원가"),
    ("외주비", "현장"): ("외주비", "공사원가"),
    ("식대/회식", "현장"): ("복리후생비", "공사원가"),
    ("간식/음료", "현장"): ("복리후생비", "공사원가"),
    ("숙박비", "현장"): ("복리후생비", "공사원가"),
    ("주유/톨비", "현장"): ("운반비", "공사원가"),
    ("차량수리", "현장"): ("운반비", "공사원가"),
    ("운송/택배", "현장"): ("운반비", "공사원가"),
    ("소모품", "현장"): ("소모품비", "공사원가"),
    ("기타잡비", "현장"): ("소모품비", "공사원가"),
    ("잡자재", "현장"): ("잡자재", "공사원가"),
    ("장비렌탈", "현장"): ("장비사용료", "공사원가"),
    ("수수료", "현장"): ("수수료비용", "공사원가"),
    # 판관비 (본사)
    ("인건비(일용/급여)", "본사"): ("직원급여", "판관비"),
    ("식대/회식", "본사"): ("복리후생비", "판관비"),
    ("간식/음료", "본사"): ("복리후생비", "판관비"),
    ("주유/톨비", "본사"): ("여비교통비", "판관비"),
    ("차량수리", "본사"): ("차량유지비", "판관비"),
    ("접대/선물", "본사"): ("기업업무추진비", "판관비"),
    ("통신비/인터넷", "본사"): ("통신비", "판관비"),
    ("전기/수도/가스", "본사"): ("세금과공과", "판관비"),
    ("세금/공과금", "본사"): ("세금과공과", "판관비"),
    ("임대료", "본사"): ("지급임차료", "판관비"),
    ("사무용품", "본사"): ("소모품비", "판관비"),
    ("도서/인쇄", "본사"): ("도서인쇄비", "판관비"),
    ("수수료", "본사"): ("수수료비용", "판관비"),
    # 기타 수입
    ("기타수입", "현장"): ("잡이익", "영업외수익"),
    ("기타수입", "본사"): ("잡이익", "영업외수익"),
}

# Define Item Lists
INCOME_ITEMS = ["공사대금수령", "기타수입"]
ALL_ITEMS = sorted(list(set([k[0] for k in MAPPING_RULES.keys()])))
EXPENSE_ITEMS = sorted([item for item in ALL_ITEMS if item not in INCOME_ITEMS])

# Fixed Orders for Reports
CONSTRUCTION_COST_ORDER = [
    "원재료비", "노무비", "외주비", "복리후생비", "감가상각비", 
    "보험료", "운반비", "잡자재", "소모품비", "수수료비용", "장비사용료"
]

SGA_ORDER = [
    "직원급여", "상여금", "복리후생비", "여비교통비", "기업업무추진비", 
    "통신비", "세금과공과", "지급임차료", "차량유지비", "도서인쇄비", 
    "소모품비", "수수료비용"
]

# --- Supabase Connection ---
@st.cache_resource
def init_supabase():
    try:
        url = st.secrets["supabase"]["url"]
        key = st.secrets["supabase"]["key"]
        return create_client(url, key)
    except Exception as e:
        st.error(f"Supabase 연결 설정 오류: {e}")
        st.stop()

supabase: Client = init_supabase()

# --- Session State Initialization ---
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False

# --- Helper Functions ---
def get_mapping(item, attribution):
    if (item, attribution) in MAPPING_RULES:
        return MAPPING_RULES[(item, attribution)]
    else:
        return item, "미분류"

def login(username, password):
    try:
        response = supabase.table("users").select("*").eq("username", username).eq("password", password).execute()
        if response.data:
            st.session_state.logged_in = True
            st.success("로그인 성공!")
            time.sleep(0.5)
            st.rerun()
        else:
            st.error("아이디 또는 비밀번호가 잘못되었습니다.")
    except Exception as e:
        st.error("로그인 중 오류가 발생했습니다.")
        st.warning("Supabase에 'users' 테이블이 없는 것 같습니다. 아래 SQL을 실행해주세요.")
        sql_query = """
-- Users 테이블 생성
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
-- 테스트 유저 데이터 삽입
INSERT INTO public.users (username, password) VALUES ('admin', '1234');
        """
        st.code(sql_query, language="sql")
        with st.expander("상세 에러 내용"):
            st.write(e)

def logout():
    st.session_state.logged_in = False
    st.rerun()

def show_login_page():
    # Custom CSS for Login Page
    st.markdown(
        """
        <style>
            [data-testid="stSidebar"] {display: none;}
            
            /* Title Style */
            .main-title {
                font-size: 50px;
                font-weight: bold;
                color: black;
                text-align: center;
                margin-bottom: 10px;
                font-family: 'Malgun Gothic', sans-serif;
            }
            
            /* Logo Style */
            .logo-icon {
                font-size: 80px;
                text-align: center;
                display: block;
                margin-bottom: 0px;
            }
            
            /* Custom Button Style */
            div.stButton > button:first-child {
                background-color: #FCE4D6 !important;
                color: #C0504D !important;
                border-radius: 15px !important;
                border: 1px solid #E0E0E0 !important;
                font-weight: bold !important;
                font-size: 18px !important;
                padding: 15px 20px !important;
                width: 100% !important;
                box-shadow: 0px 2px 5px rgba(0,0,0,0.1) !important;
            }
            div.stButton > button:hover {
                background-color: #F2D7C6 !important;
                color: #A0302D !important;
                border: 1px solid #C0C0C0 !important;
            }
            
            /* Input fields styling */
            div[data-baseweb="input"] {
                border-radius: 10px;
                border: 1px solid #CCCCCC !important;
                background-color: #FFFFFF !important;
            }
            input {
                color: #000000 !important;
            }
        </style>
        """,
        unsafe_allow_html=True
    )

    col1, col2, col3 = st.columns([1, 1.5, 1])
    
    with col2:
        st.markdown('<div class="logo-icon">🔺</div>', unsafe_allow_html=True)
        st.markdown('<div class="main-title">세무의 모든 것</div>', unsafe_allow_html=True)
        
        st.write("") 
        st.write("") 
        
        username = st.text_input("아이디", placeholder="아이디를 입력하세요", label_visibility="collapsed")
        st.write("") 
        password = st.text_input("비밀번호", type="password", placeholder="비밀번호를 입력하세요", label_visibility="collapsed")
        
        st.write("") 
        st.write("") 
        
        if st.button("로그인"):
            login(username, password)

def show_history_page():
    st.markdown("### 📋 내역 수정/삭제")
    try:
        response = supabase.table("transactions").select("*").order("date", desc=True).execute()
        rows = response.data
        if not rows:
            st.info("입력된 내역이 없습니다.")
        else:
            df = pd.DataFrame(rows)
            df['date'] = pd.to_datetime(df['date'])
            
            column_config = {
                "id": None,
                "created_at": None,
                "user_id": None,
                "date": st.column_config.DateColumn("날짜", format="YYYY-MM-DD"),
                "type": "구분",
                "attribution": "귀속",
                "category_raw": "항목(일상어)",
                "category_std": "계정과목(표준)",
                "account_type": "회계분류",
                "amount": st.column_config.NumberColumn("금액", format="%d원"),
                "vendor": "거래처",
                "memo": "메모"
            }
            
            edited_df = st.data_editor(
                df,
                column_config=column_config,
                use_container_width=True,
                num_rows="dynamic",
                key="history_editor"
            )
            
            if st.button("변경사항 저장하기", use_container_width=True):
                try:
                    changes = st.session_state["history_editor"]
                    for index, updates in changes["edited_rows"].items():
                        row_id = df.iloc[index]["id"]
                        supabase.table("transactions").update(updates).eq("id", row_id).execute()
                    for index in changes["deleted_rows"]:
                        row_id = df.iloc[index]["id"]
                        supabase.table("transactions").delete().eq("id", row_id).execute()
                    for new_row in changes["added_rows"]:
                        clean_row = {k: v for k, v in new_row.items() if v is not None}
                        if clean_row:
                            supabase.table("transactions").insert(clean_row).execute()

                    if changes["edited_rows"] or changes["deleted_rows"] or changes["added_rows"]:
                        st.success("수정/삭제가 완료되었습니다.")
                        time.sleep(1)
                        st.rerun()
                    else:
                        st.info("변경사항이 없습니다.")
                except Exception as e:
                    st.error(f"저장 중 오류 발생: {e}")
    except Exception as e:
        st.error("데이터를 불러오는 중 오류가 발생했습니다.")
        st.write(e)

def show_report_page():
    st.markdown("### 📊 보고서 요약")
    
    try:
        response = supabase.table("transactions").select("*").execute()
        rows = response.data
        
        if not rows:
            st.info("데이터가 없습니다.")
            return

        df = pd.DataFrame(rows)
        df['date'] = pd.to_datetime(df['date'])
        df['amount'] = df['amount'].astype(int)
        
        # --- Data Processing ---
        income_df = df[df['type'] == '수입']
        expense_df = df[df['type'] == '지출']
        
        site_expense_df = expense_df[expense_df['attribution'] == '현장']
        hq_expense_df = expense_df[expense_df['attribution'] == '본사']
        
        total_revenue = income_df['amount'].sum()
        total_site_expense = site_expense_df['amount'].sum()
        total_hq_expense = hq_expense_df['amount'].sum()
        
        # --- Section 1: Dashboard ---
        st.subheader("1. 경영 대시보드")
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("##### 현장 vs 본사 비용 비중")
            if total_site_expense + total_hq_expense > 0:
                pie_data = pd.DataFrame({
                    "Category": ["공사원가 (현장)", "판관비 (본사)"],
                    "Amount": [total_site_expense, total_hq_expense]
                })
                fig_pie = px.pie(pie_data, values='Amount', names='Category', hole=0.4)
                st.plotly_chart(fig_pie, use_container_width=True)
            else:
                st.caption("비용 데이터가 없습니다.")

        with col2:
            st.markdown("##### 월별 지출 추이")
            if not expense_df.empty:
                expense_df['month'] = expense_df['date'].dt.strftime('%Y-%m')
                monthly_expense = expense_df.groupby('month')['amount'].sum().reset_index()
                fig_bar = px.bar(monthly_expense, x='month', y='amount', text_auto=',.0f')
                st.plotly_chart(fig_bar, use_container_width=True)
            else:
                st.caption("지출 데이터가 없습니다.")

        st.divider()

        # --- Section 2: Construction Cost Statement (공사원가명세서) ---
        st.subheader("2. 공사원가명세서 (현장)")
        
        if not site_expense_df.empty:
            site_grouped = site_expense_df.groupby('category_std')['amount'].sum()
        else:
            site_grouped = pd.Series(dtype=int)

        cost_data = []
        for category in CONSTRUCTION_COST_ORDER:
            amount = site_grouped.get(category, 0)
            cost_data.append({"항목": category, "금액": amount})
        
        cost_statement_df = pd.DataFrame(cost_data)
        total_row = pd.DataFrame({'항목': ['당기총공사비용(합계)'], '금액': [total_site_expense]})
        cost_statement_final = pd.concat([cost_statement_df, total_row], ignore_index=True)
        
        st.dataframe(
            cost_statement_final,
            column_config={"금액": st.column_config.NumberColumn("금액", format="%d원")},
            use_container_width=True,
            hide_index=True
        )

        st.divider()

        # --- Section 3: Income Statement (손익계산서) ---
        st.subheader("3. 손익계산서")
        
        gross_profit = total_revenue - total_site_expense
        operating_profit = gross_profit - total_hq_expense
        
        is_summary_data = {
            "항목": ["1. 매출액", "2. 매출원가 (공사원가)", "3. 매출총이익 (1-2)", "4. 판매비와관리비", "5. 영업이익 (3-4)"],
            "금액": [total_revenue, total_site_expense, gross_profit, total_hq_expense, operating_profit]
        }
        is_summary_df = pd.DataFrame(is_summary_data)
        
        st.markdown("##### 요약")
        st.dataframe(
            is_summary_df,
            column_config={"금액": st.column_config.NumberColumn("금액", format="%d원")},
            use_container_width=True,
            hide_index=True
        )

        st.markdown("##### 판매비와관리비 상세")
        if not hq_expense_df.empty:
            hq_grouped = hq_expense_df.groupby('category_std')['amount'].sum()
        else:
            hq_grouped = pd.Series(dtype=int)
            
        sga_data = []
        for category in SGA_ORDER:
            amount = hq_grouped.get(category, 0)
            sga_data.append({"항목": category, "금액": amount})
            
        sga_df = pd.DataFrame(sga_data)
        
        st.dataframe(
            sga_df,
            column_config={"금액": st.column_config.NumberColumn("금액", format="%d원")},
            use_container_width=True,
            hide_index=True
        )
        
        # --- Excel Download ---
        st.divider()
        
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
            cost_statement_final.to_excel(writer, sheet_name='공사원가명세서', index=False)
            is_summary_df.to_excel(writer, sheet_name='손익계산서', index=False, startrow=0)
            start_row = len(is_summary_df) + 3
            pd.DataFrame(["[판매비와관리비 상세]"]).to_excel(writer, sheet_name='손익계산서', index=False, header=False, startrow=start_row-1)
            sga_df.to_excel(writer, sheet_name='손익계산서', index=False, startrow=start_row)
            df.to_excel(writer, sheet_name='전체데이터', index=False)
            
        st.download_button(
            label="📥 엑셀 다운로드 (세무신고용)",
            data=buffer.getvalue(),
            file_name=f"건설회계_세무신고용_{pd.Timestamp.now().strftime('%Y%m%d')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True
        )

    except Exception as e:
        st.error("보고서를 생성하는 중 오류가 발생했습니다.")
        st.write(e)

# --- Main Execution ---
def main():
    if not st.session_state.logged_in:
        show_login_page()
    else:
        # Header Area
        col_header_left, col_header_right = st.columns([8, 2])
        
        with col_header_left:
            # Small Logo or Empty
            st.markdown("### 🏗️") 

        with col_header_right:
            # User Profile and Logout
            st.markdown("<div style='text-align: right; margin-bottom: 5px;'><b>👤 (주)부름 님</b></div>", unsafe_allow_html=True)
            if st.button("로그아웃", use_container_width=True):
                logout()

        st.divider()
        
        # Tabs
        tab1, tab2, tab3 = st.tabs(["📥 수입/지출 입력", "📋 내역 수정/삭제", "📊 보고서 요약"])

        # --- Tab 1: Input ---
        with tab1:
            col_income, col_expense = st.columns(2)
            
            # --- Income Column ---
            with col_income:
                st.markdown("<h2 style='text-align: center;'>⬇️💰</h2>", unsafe_allow_html=True)
                st.markdown("<h3 style='text-align: center;'>입금 (수입)</h3>", unsafe_allow_html=True)
                
                with st.form("income_form"):
                    date_in = st.date_input("날짜", key="in_date")
                    site_in = st.text_input("현장명 (필수)", placeholder="어디서 들어온 돈인가요?")
                    item_in = st.selectbox("항목", INCOME_ITEMS)
                    amount_in = st.number_input("금액 (필수)", min_value=0, value=None, placeholder="입금액을 입력하세요 (숫자만)")
                    memo_in = st.text_input("메모", placeholder="비고 사항")
                    
                    submit_in = st.form_submit_button("입금 내역 저장", use_container_width=True)
                    
                    if submit_in:
                        if not site_in or amount_in is None:
                            st.error("현장명과 금액을 입력해주세요.")
                        else:
                            # Income Mapping Logic
                            cat_std, acc_type = get_mapping(item_in, "현장")
                            
                            try:
                                data = {
                                    "date": str(date_in),
                                    "type": "수입",
                                    "attribution": "현장", 
                                    "category_raw": item_in, 
                                    "category_std": cat_std,
                                    "account_type": acc_type,
                                    "amount": amount_in,
                                    "vendor": site_in,
                                    "memo": memo_in
                                }
                                supabase.table("transactions").insert(data).execute()
                                st.success("✅ 입금 내역이 저장되었습니다.")
                                st.info(f"분류: {cat_std} ({acc_type})")
                            except Exception as e:
                                st.error(f"저장 실패: {e}")

            # --- Expense Column ---
            with col_expense:
                st.markdown("<h2 style='text-align: center;'>⬆️💸</h2>", unsafe_allow_html=True)
                st.markdown("<h3 style='text-align: center;'>출금 (지출)</h3>", unsafe_allow_html=True)
                
                with st.form("expense_form"):
                    date_out = st.date_input("날짜", key="out_date")
                    attribution_out = st.radio("귀속", ["현장", "본사"], horizontal=True)
                    item_out = st.selectbox("항목", EXPENSE_ITEMS)
                    amount_out = st.number_input("금액 (필수)", min_value=0, value=None, placeholder="지출액을 입력하세요 (숫자만)")
                    memo_out = st.text_input("메모", placeholder="거래처명, 상세 내용 등")
                    
                    submit_out = st.form_submit_button("지출 내역 저장", use_container_width=True)
                    
                    if submit_out:
                        if amount_out is None:
                            st.error("금액을 입력해주세요.")
                        else:
                            cat_std, acc_type = get_mapping(item_out, attribution_out)
                            try:
                                data = {
                                    "date": str(date_out),
                                    "type": "지출",
                                    "attribution": attribution_out,
                                    "category_raw": item_out,
                                    "category_std": cat_std,
                                    "account_type": acc_type,
                                    "amount": amount_out,
                                    "vendor": "", 
                                    "memo": memo_out
                                }
                                supabase.table("transactions").insert(data).execute()
                                st.success("✅ 지출 내역이 저장되었습니다.")
                                st.info(f"분류: {cat_std} ({acc_type})")
                            except Exception as e:
                                st.error(f"저장 실패: {e}")

        # --- Tab 2: History ---
        with tab2:
            show_history_page()

        # --- Tab 3: Report ---
        with tab3:
            show_report_page()

if __name__ == "__main__":
    main()
