[supabase]
url = "https://uqrkwvjerfhyspqoeigt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcmt3dmplcmZoeXNwcW9laWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjQwNzIsImV4cCI6MjA4Mjk0MDA3Mn0.8jvzYdvtEfpeK9WjBmjgMdXAzaa3BCeo1DVywPTEvHc"